/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import komunikacija.Komunikacija;
import model.Igra;
import niti.BrojNiti;
import operacije.Operacije;
import transfer.KlijentskiZahtev;
import transfer.ServerskiOdgovor;

/**
 *
 * @author munja
 */
public class KlijentskaForma extends javax.swing.JFrame {

    BrojNiti nit1;
    BrojNiti nit2;
    BrojNiti nit3;
    BrojNiti nit4;
    
    private int brojPokusaja = 0;
    /**
     * Creates new form KlijentskaForma
     */
    public KlijentskaForma() {
        initComponents();
        
        
        ModelTabeleIgra mti = new ModelTabeleIgra();
        jTableIgra.setModel(mti);
        //popuniTabelu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelBroj2 = new javax.swing.JLabel();
        jLabelBroj3 = new javax.swing.JLabel();
        jLabelBroj4 = new javax.swing.JLabel();
        jLabelBroj1 = new javax.swing.JLabel();
        jButtonStart1 = new javax.swing.JButton();
        jButtonStop1 = new javax.swing.JButton();
        jButtonStart2 = new javax.swing.JButton();
        jButtonStop2 = new javax.swing.JButton();
        jButtonStart3 = new javax.swing.JButton();
        jButtonStop3 = new javax.swing.JButton();
        jButtonStart4 = new javax.swing.JButton();
        jButtonStop4 = new javax.swing.JButton();
        jButtonPosalji = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelNaMestu = new javax.swing.JLabel();
        jLabelVanMesta = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableIgra = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelBroj2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabelBroj2.setText("0");

        jLabelBroj3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabelBroj3.setText("0");

        jLabelBroj4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabelBroj4.setText("0");

        jLabelBroj1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabelBroj1.setText("0");

        jButtonStart1.setText("start 1");
        jButtonStart1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStart1ActionPerformed(evt);
            }
        });

        jButtonStop1.setText("stop 1");
        jButtonStop1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStop1ActionPerformed(evt);
            }
        });

        jButtonStart2.setText("start 2");
        jButtonStart2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStart2ActionPerformed(evt);
            }
        });

        jButtonStop2.setText("stop 2");
        jButtonStop2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStop2ActionPerformed(evt);
            }
        });

        jButtonStart3.setText("start 3");
        jButtonStart3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStart3ActionPerformed(evt);
            }
        });

        jButtonStop3.setText("stop 3");
        jButtonStop3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStop3ActionPerformed(evt);
            }
        });

        jButtonStart4.setText("start 4");
        jButtonStart4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStart4ActionPerformed(evt);
            }
        });

        jButtonStop4.setText("stop 4");
        jButtonStop4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStop4ActionPerformed(evt);
            }
        });

        jButtonPosalji.setText("posalji");
        jButtonPosalji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPosaljiActionPerformed(evt);
            }
        });

        jLabel1.setText("NA MESTU");

        jLabel2.setText("NISU NA MESTU");

        jTableIgra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableIgra);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(170, 170, 170)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelNaMestu)
                            .addComponent(jLabelVanMesta)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 111, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabelBroj1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonStop1)
                    .addComponent(jButtonStart1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonStop2)
                            .addComponent(jButtonStart2))
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonStart3)
                            .addComponent(jButtonStop3))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonStop4)
                            .addComponent(jButtonStart4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabelBroj2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(jLabelBroj3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jLabelBroj4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(jButtonPosalji)))
                .addGap(61, 61, 61))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonStart1)
                    .addComponent(jButtonStart2)
                    .addComponent(jButtonStart3)
                    .addComponent(jButtonStart4))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelBroj2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelBroj3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelBroj4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelBroj1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jButtonPosalji)))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonStop1)
                    .addComponent(jButtonStop2)
                    .addComponent(jButtonStop3)
                    .addComponent(jButtonStop4))
                .addGap(98, 98, 98)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelNaMestu))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabelVanMesta))
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonStart2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStart2ActionPerformed
        nit2 = new BrojNiti(jLabelBroj2);
        nit2.start();
    }//GEN-LAST:event_jButtonStart2ActionPerformed

    private void jButtonStart1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStart1ActionPerformed
        nit1 = new BrojNiti(jLabelBroj1);
        nit1.start();
    }//GEN-LAST:event_jButtonStart1ActionPerformed

    private void jButtonStop1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStop1ActionPerformed
        nit1.zaustaviNit();
    }//GEN-LAST:event_jButtonStop1ActionPerformed

    private void jButtonStop2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStop2ActionPerformed
        nit2.zaustaviNit();
    }//GEN-LAST:event_jButtonStop2ActionPerformed

    private void jButtonStart3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStart3ActionPerformed
        nit3 = new BrojNiti(jLabelBroj3);
        nit3.start();
    }//GEN-LAST:event_jButtonStart3ActionPerformed

    private void jButtonStart4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStart4ActionPerformed
        nit4 = new BrojNiti(jLabelBroj4);
        nit4.start();
    }//GEN-LAST:event_jButtonStart4ActionPerformed

    private void jButtonStop3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStop3ActionPerformed
        nit3.zaustaviNit();
    }//GEN-LAST:event_jButtonStop3ActionPerformed

    private void jButtonStop4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStop4ActionPerformed
        nit4.zaustaviNit();
    }//GEN-LAST:event_jButtonStop4ActionPerformed

    private void jButtonPosaljiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPosaljiActionPerformed
        
        if(brojPokusaja<=5){
        String kombinacija = jLabelBroj1.getText() + "-" + jLabelBroj2.getText() + "-" + jLabelBroj3.getText() + "-" + jLabelBroj4.getText();
        
        System.out.println(kombinacija);
        
        Igra igra = new Igra(-1, kombinacija, -1, -1);
        KlijentskiZahtev kz = new KlijentskiZahtev(Operacije.POGADJAJ, igra);
        Komunikacija.getInstance().posaljiZahtev(kz);
        
        ServerskiOdgovor so = Komunikacija.getInstance().primiOdgovor();
        igra = (Igra) so.getOdgovor();
        
        brojPokusaja++;
        
        jLabelNaMestu.setText(igra.getBrPogodjenihNaMestu() + "");
        jLabelVanMesta.setText(igra.getBrPogodjenihNisuNaMestu() + "");
        
        ModelTabeleIgra mti = (ModelTabeleIgra) jTableIgra.getModel();
        mti.dodajIgru(igra);
        }else{
            System.out.println("NEMA VISE POKUSAJA");
        }
        
    }//GEN-LAST:event_jButtonPosaljiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KlijentskaForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPosalji;
    private javax.swing.JButton jButtonStart1;
    private javax.swing.JButton jButtonStart2;
    private javax.swing.JButton jButtonStart3;
    private javax.swing.JButton jButtonStart4;
    private javax.swing.JButton jButtonStop1;
    private javax.swing.JButton jButtonStop2;
    private javax.swing.JButton jButtonStop3;
    private javax.swing.JButton jButtonStop4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelBroj1;
    private javax.swing.JLabel jLabelBroj2;
    private javax.swing.JLabel jLabelBroj3;
    private javax.swing.JLabel jLabelBroj4;
    private javax.swing.JLabel jLabelNaMestu;
    private javax.swing.JLabel jLabelVanMesta;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableIgra;
    // End of variables declaration//GEN-END:variables

    private void popuniTabelu() {
        
        ModelTabeleIgra mti = new ModelTabeleIgra();
        jTableIgra.setModel(mti);
    }
}
